name: Bug Report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How did you encounter this bug?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., v2.4.0